spring:
   datasource:
      dynamic:
         primary: master #设置默认的数据源或者数据源组，默认值即为master
         #如果你只是单数据源，则只需要注释掉slave相关配置就好了，这里为了方便演示master与slave保持相同
         datasource:
            master:
               driverClassName: com.mysql.jdbc.Driver
               url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
               username: root
               password: root
            slave_1:
               driverClassName: com.mysql.jdbc.Driver
               url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
               username: root
               password: root
server:
   port: 9090